server:
  port: 8005

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://first-service
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8087/
          predicates:
            - Path=/second-service/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG